project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: Intermediate Microeconomics
  description: Materials for CASED's pre-Master course in Microeconomics
  
  # site-url: ""
  # repo-url: ""
  
  open-graph: true

  # page-footer: 

  navbar:
    background: "#33404d"
    left:
      - text: Home
        href: index.qmd
      # - text: About
        # href: about.qmd
      - text: Contact
        href: contact.qmd
  
  sidebar: 
    background: "#D3D3D3"
    style: docked
    collapse-level: 2
    pinned: true
    contents:
      - section: "Course information"
        contents:
          - text: "Schedule"
            href: index.qmd
          - text: "References"
            href: contents/references.qmd
      - section: "Lectures"
        contents:
          - text: "Lecture 1"
            href: contents/lecture_1.qmd
          - text: "Lecture 2"
            href: contents/lecture_2.qmd
          - text: "Lecture 3"
            href: contents/lecture_3.qmd
          - text: "Lecture 4"
            href: contents/lecture_4.qmd
          - text: "Lecture 5"
            href: contents/lecture_5.qmd

format:
  html:
    theme: 
      light: lux
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    mermaid:
      theme: neutral






