---
title: "Course plan"
---

In this page you will find a tentative outline of the course. The last meeting will be dedicated to a revision of the topics covered, exam preparation and Q&As.

::: column-screen-inset-right
+-------------+------------------------------------------------------------------+-------------------------------------------+
| Lecture     | Topics                                                           | References                                |
+:===========:+:=================================================================+:==========================================+
| 1           | **Consumers and demand**                                         | Chapter 1 (AF Adv)                        |
|             |                                                                  |                                           |
|             | -   Properties of the preference relation                        |                                           |
|             | -   Utility representation                                       |                                           |
|             | -   Consumer choice and demand function                          |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 2           | **Consumers and demand (cont)**                                  | Chapter 1 (AF Adv)                        |
|             |                                                                  |                                           |
|             | -   Properties of utility functions                              |                                           |
|             | -   Utility maximization, Walrasian demand and properties        |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 3           | **Firms and supply**                                             | Chapter 7-8 (AF Int)                      |
|             |                                                                  |                                           |
|             | -   Firms and production function                                |                                           |
|             | -   Expenditure minimization problem and cost function           |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 4           | **Competitive markets and general equilibrium**                  | Chapter 9 (AF Int) or Chapter 24 (Varian) |
|             |                                                                  |                                           |
|             | -   Profit maximization problem                                  |                                           |
|             | -   Short-run and long-run supply and partial equilibrium        |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 5           | **Competitive markets and general equilibrium (cont)**           | Chapter 9 (AF Int) or Chapter 24 (Varian) |
|             |                                                                  |                                           |
|             | -   General equilibrium in a pure exchange economy               |                                           |
|             |                                                                  |                                           |
|             | -   Welfare theorems                                             |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 6           | **Monopoly**                                                     | Chapter 7 (AF Adv)                        |
|             |                                                                  |                                           |
|             | -   Monopoly and profit maximization                             |                                           |
|             | -   Lerner index and IEPR                                        |                                           |
|             | -   Welfare analysis and public policy                           |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 7           | **Game theory primer and applications in imperfect competition** | Chapter 12-14 (AF Int)                    |
|             |                                                                  |                                           |
|             | -   Definition, solution concepts and representation             |                                           |
|             | -   Common simultaneous and sequential games                     |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 8           | **Exerternalities and public goods**                             | Chapter 17 (AF Int)                       |
|             |                                                                  |                                           |
|             | -   Implications on the efficiency of competitive equilibria     |                                           |
|             | -   Common policy remedies                                       |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 9           | **Choice under uncertainty**                                     | Chapter 5 (AF Adv)                        |
|             |                                                                  |                                           |
|             | -   Lotteries and preferences over lotteries                     |                                           |
|             | -   Expected utility theory                                      |                                           |
|             | -   Applications                                                 |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
| 10          | **Revision**                                                     |                                           |
+-------------+------------------------------------------------------------------+-------------------------------------------+
:::