---
title: "Chapter 7. Externalities and public goods"
author:
    name: My Dam
    email: my-thi-tra.dam@universite-paris-saclay.fr
number-sections: true
execute:
    echo: false
format:
    html:
        toc: true
        toc-depth: 3
        toc-title: "Content"
        # toc-expand: true
        toc-location: "left"
        # embed-resources: true
---


```{python}
%load_ext autoreload
%autoreload 2
```

```{python}
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
import pandas as pd
import dataframe_image as dfi
import ipywidgets as widgets
from IPython.display import display
from ipywidgets import interact
import pandas as pd
```

```{python}
import sys
import os
mod_dir = os.path.join(os.getcwd(), 'modules')
if mod_dir not in sys.path:
    sys.path.append(mod_dir)

import micro_modules as mm
mm.load_viz_settings()
```

Just like market power, externalities and public goods are two other causes of market failures. In presence of externalities or public goods, the competitive market fails to produce an efficient outcome. In this chapter, we will be analyzing these problems and their common solutions. 

# Externalities

## Definition and examples

An externality is the effect that agent has on the welfare of another agent beyond the effects transmitted by changes in prices.
It typically represents an effect imposed on or benefited by a third party to an exchange/transaction.

::: {#tbl-ext-exm tbl-cap="Externalities: types and examples"}
<table style="text-align:left; width=100%">
    <tr>
        <th></th>
        <th>Negative</th>
        <th>Positive</th>
    </tr>
    <tr>
        <th align=left>From consumption</th>
        <td>
            <ul>
                <li>Passive smoking</li>
                <li>Noisy neighbors</li>
            </ul>
        </td>
        <td>
            <ul>
                <li>Vaccination</li>
                <li>Education</li>
            </ul>
        </td>
    </tr>
    <tr>
        <th>From production</th>
        <td>
            <ul>
                <li>Air pollution by coal-powered power stations</li>
                <li>Water contamination by a firm that dumps industrial wastes directly into the river</li>
            </ul>
        </td>
        <td>
            <ul>
                <li>Unpatented research and development</li>
                <li>Apiculture</li>
            </ul>
        </td>
    </tr>
</table>
:::

## Modeling externalities

Consider a economy with two types of agents: a firm and a consumer. The firm's productive activities generate negative externalities that affect the consumer.

### The representative firm

The firm's objective is to maximize profit $\pi(x,p)$ where $p$ is the price vector and $x$ the amount of externality generated. In a competitive market the firm is a price taker, taking $p$ as given, allowing us to write the profit function s $\pi(x).$ We assume that the profit functionis twice differentiable, increasing and concave:

$$
\pi'(x) > 0 > \pi''(x).
$${#eq-assumption-profit}

In words, we assume that profits increase with externalities since the firm does not bear the full marginal cost of production. Nevertheless, the marginal benefits of pollution decline. Note that since externalities are generated by production, making decision on externalities can be considered equivalent to making decision on output, as illustrated in @exm-eqm-ext.

### The reprsentative consumer

The consumer has preferences reprsented by an utility function $u(q,x),$ where $q\in\mathbb{R}_+^n$ is the consumption bundle, the vector of _tradable goods_, and $x$ is the negative externatlity, which is _not tradable_ (otherwise it would have had a price and the impact would have been internalized!). We assume:

$$
u_k \equiv \frac{\partial u}{\partial q_k} \geq 0,\quad \forall k=1,\dots,n.
$${#eq-assume-u-q}

and

$$
u_x \equiv \frac{\partial u}{\partial x} \lt 0.
$${#eq-assum-u-x}

Denote $w$ the consumer's income and $q^*(p,w,x)$ the Walrasian demand function. Then the indirect utility function (the maximized utility function) is:

$$
    v(x) = u(q*(p,w,x),x).
$${#eq-indirect-u}

Observe that $v'(x)<0$ for all $x>0.$

### Competitive and pareto equilibrium externality

In a competitive equilibrium, the firm selects the (private) level of externatlity that maximizes its profits:

$$
x^P = \arg\max_{x\geq 0} \pi(x),
$${#eq-firm-CE}

The FOC of which yields (for an interior solution):

$$
\pi'(x^P) = 0,.
$${#eq-foc-CE}


In a Pareto equilibrium, the social planner selects the level of externality that maximizes the sum of profits and utilities:

$$
x^E = \arg\max_{x\geq 0} \pi(x) + v(x).
$${#eq-SP}

The necessary condition for an interior solution ($x^E>0$) is:

$$
\pi'(x^E) = - v'(x^E).
$${#eq-FOC-SP}

In other words, the social planner selects a level of externality such that the marginal benefit derived from it by the firm is equal to the marignal cost (disutility) suffered by the consumer.

Since $v'(x)<0,$ and $\pi''(x)<0,$ we have:

$$
\begin{aligned}
\pi'(x^E) > 0 &= \pi'(x^P) \\
x^E &< x^P.
\end{aligned}
$$

Hence the Pareto efficient level of pollution, $x^E$ is less than the competitve level $x^P$ selected by the firm. 

::: {#exm-eqm-ext}
## Negative externalities
Consider a firm with $\pi = pq - cq^2$ where $q$ is the output, $p$ is the price of the good and $c>0$ is a constant. Suppose that externality is a linear function of quantity, namely $x=a q,$ with $a >0.$ Hence:

$$
\pi(x) = p\frac{x}{a} - c\left(\frac{x}{a}\right)^2.
$$

The FOC yields:
$$
x^P = \frac{ap}{2c}.
$$

Suppose that the consumer has a damange function defined by:

$$
v(x) = b - cx - \frac{dx^2}{2},\quad b,d>0.
$$
Observe that the marginal cost of the damage increases in the level of pollution. This makes sense intuitively if we think about how health deterioration accelerates as pollution gets worse.

In view of @eq-FOC-SP, we can determine the Pareto efficient level of externality:

$$
\begin{aligned}
\pi'(x^E) &= -v'(x^E) \\
\frac{p}{a}-\frac{2c}{a^2}x^E &= c+dx^E \\
x^E &= \frac{ap-a^2c}{2c+ad}.
\end{aligned}
$$

When is it efficient to have a positive amount of externality, i.e., to have $x^E>0?$ Observe that $v'(0)=-c$ and $\pi'(0)=p/a$ and $x^E > 0$ if and only if $pa-ca^2 >0,$ which is equivalent to $p/a > c$ or $\pi'(0)>-v'(0).$ In other words, the economy should generate negative externalities if the marginal benefits of doing so for firms are greater than the marginal costs to consumers at the origin.
::: 

::: {#exm-positive-ext}
## Positive externalities
Consider two neighboring countries, $i$ and $j,$ simultaneously choosing the level of investment in recycling activities $x_i.$ The benefit from recycling is given by:

$$
\pi_i(x_i,x_j) = (a - 0.5x_i + 0.25x_j)x_i - bx_i,
$$

where $a,b>0.$

In a competitive equilibrium, country $i$ chooses $x_i$ so as to maximize its own benefit. The optimal conditions provide the best response functions for the firms. In particular:
$$
\begin{aligned}
\frac{\partial{\pi_i}}{\partial x_i} = 0
\iff x_i &= a - b + \frac{x_j}{4} \\
BR_i(x_j) &= a - b + \frac{x_j}{4},
\end{aligned}
$$

and likewise for country $j.$

The NE of this game is:
$$
x_i^* = x_j^* = \frac{4(a - b)}{3}.
$${#eq-NE-comp}

To be Pareto optimal, each country considers not only its own benefit but also that of the other country when making a decision. Another way to think about this is to make a decision from the point of view of a social planner who determines both investment levels to maximize joint benefits:

$$
\max_{x_i,x_j} \pi(x_i,x_j) \equiv \pi_i(x_i,x_j) + \pi_j(x_i,x_j).
$${#eq-pos-ext-SP}

The FOC condition for country $i$ gives:

$$
\begin{aligned}
\frac{\partial \pi}{\partial x_i} &= 0 \\
\frac{\partial \pi_i(x_i,x_j)}{\partial x_i} + \frac{\partial \pi_j(x_i,x_j)}{\partial x_i} &= 0 \\
x_i &= a - b + \frac{x_j}{2}.
\end{aligned}
$$

Likewise for country $j:$ 

$$
x_j = a - b + \frac{x_i}{2}.
$$

Hence the best response lines are steeper compared to the competitive case, resulting in higher equilibrium investments. In particular, the socially efficient NE is:

$$
x_i^E = x_j^E = 2(a-b).
$$
:::

## Solutions to externalities

Externalities lead to an inefficient equilibrium quantity. In the case of negative externalities, the party generating externalities does not fully bear the cost of the production or consumption of the good. Consequently, the economy tends to overproduce or overconsume.
In the case of positive externalities, it is the converse. The party generating externalities does not consider the benefits of their consumption or production activities enjoyed by other parties, hence tend to underproduce or underconsume. In either cases, the inefficient quantity leads to a deadweight loss. There are two approaches to address the problem of externalities. One is based on the clear establishment of property rights and the negotiation among the parties involved. When transaction costs become prohibitive, private negotiation might not be possible, calling for public intervention. The most popular forms of public policy interventions include quotas, Pigouvian taxation (or subsidization) and tradable permits.

### Private solution

According to the **Coase theorem**, in absence of transaction costs and presence of well-established property rights, the two parties can negotiate to achieve an efficient level of externality.

The result of the negotation will typically be a transfer _to the party that has the property rights_ from the other party. Note that it does not matter who suffers from negative externalities, the party that is supposed to be compensated is the property rights holder.

::: {#exm-neg-ext-sol-private}
## Private solution to negative externalities
Consider again @exm-eqm-ext and suppose that the party suffering from negative externalities, the consumer, has the property rights. The firm makes a lump-sum transfer $T>0$ to the consumer if and only if:

$$
\pi(x) - T \geq \pi(0),
$$

which can be viewed as the participation constraint of the firm. Given this condition, the consumer determines $T,x$ that maximizes her welfare:

$$
\begin{aligned}
&\max_{x\geq 0, T} w + v(x) + T \\
\text{s.t. }& \pi(x) - T \geq \pi(0),
\end{aligned}
$$

where $w$ is the initial wealth of the consumer.
Observe that the participation constraint binds at the optimum (otherwise the consumer could just demand a larger transfer). We can rewrite the consumder's program as:

$$
\max_{x\geq 0, T} v(x) + \pi(x) + w - \pi(0).
$$

The FOC yields:

$$
\pi'(x) \leq -v'(x), \quad \text{with equality for } x > 0.
$${#eq-FOC-coase}

Observe that the optimality condition ([-@eq-FOC-coase]) coincides with that of the SP's problem (@eq-FOC-SP). This implies that the solution to this problem is also Pareto efficient.
:::

What if the property rights are assigned to the firm, the party that generates externalities? In this case the consumer will make a transfer to the firm to reduce externalities.

::: {#exr-sol-private}
Show that an efficient level of externality is also achieved when the firm is the holder of the property rights. Hints:

1. The consumer will offer the firm a payment of $T$ to reduce externalities to $x$
2. Without negotation, the firm chooses the level of externality $x^P$ which maximizes its profits. What will be the participation constraint of the firm?
3. The consumer solves the UMP to determine the optimal levels of $x$ and $T,$ taking into account the partcipation constraint of the firm
4. Does the constraint bind at the optimum?
5. What is the optimality condition? Does it suggest that the externality level selected by the consumer is Pareto efficient?
:::

There are advantages and disadvantages associated with the private solution to the externality problem proposed by the Coase theorem. In particular, the disadvantages include:

* Property rights must be clearly defined and enforced
* Transaction costs must be sufficiently small

The advantage of the private solution is that there is no need for regulator's intervention (except possibily in the assignment and enforcement of property rights). 


### Public solution

#### Quota

One public solution is imposing a quota equal to the Pareto-efficient level of externality. Anything beyond that will be subject to a fine. The disadvantage of this approach is that the social planner must have perfect information about the benefits and the costs of externalities (in order to determine the efficient externality level of _each_ firm).

#### Pigouvian taxation

An alternative solution is the Pigouvian taxation (on negative externalities) and Pigouvian subsidies (for positive externalities).

The Pigouvian **tax** sets the unit price of externality. The firm's PMP becomes:

$$
\max_{x\geq 0} \pi(x) - tx,
$${#eq-PMP-avec-taxe}

where $t$ is the magnitude of the tax.
The FOC gives:

$$
\pi'(x) \leq t,\quad\text{with equality for } x >0.
$${#eq-FOC-PMP-avec-tax}

In order to incentivize $x^E,$ the Pareto-efficient externality level, the tax must be such that:

$$
-v'(x^E) = t.
$${#eq-Pigou-tax}

The tax thus induces the firm to internalize the externality it inflicts on the consumer. 

The Pigouvian __subsidy__ is a reward to the firm producing any unit beyond its competitive level (and approaching the socially efficient level). The PMP in this case reads:

$$
\max_{x\geq 0} \pi(x) + s(x^E - x).
$${#eq-PMP-avec-subsidy}

The FOC yields:

$$
\pi'(x) \leq s,\quad\text{with equality for } x >0.
$${#eq-FOC-PMP-avec-tax}

The magnitude of the subsidy must be equal to the marginal benefit received by the consumer, namely:

$$
s = -v'(x^E).
$${#eq-Pigou-sub}

Under complete information, setting quotas and taxing or subsidizing are equivalent.

#### Tradable permits

The public authority controls the quantity of externality by creating a number of permits, typically pollution permits, each of which grants the right to a fixed level of pollution. Firms can trade permits, thereby creating a market for pollution rights (or carbon market). The price of pollution is determined by market forces rather than being set by the authority.

Each firm $j$ has a permit that grants them $\bar{x}_j$ units of pollution. The authority controls the aggregate level of pollution by setting:

$$
x^E = \sum_j \bar{x}_j.
$$

Each firm $j,$ being the price-taker in the pollution market, solves:

$$
\max_{x_j \geq 0} \pi_j(x_j) + p(\bar{x}_j - x_j),
$$

where $p$ is the price the firm needs to pay for the rights to pollute beyond its permit's allowance. 

The FOC yields:

$$
\pi'_j(x_j) - p \leq 0, \quad \text{with equality for } x > 0.
$$

In equilibrium, the price of a permit has to be such that the market clears, namely:

$$
x^E = \sum_j x_j(p), 
$$

i.e., some firms might pollute more, some firms less, but in equilibrium aggregate demand (RHS) must be equal to aggregate supply. The advantage of this approach is that the public authority only needs to gather information at the aggregate level to determine $x^E,$ the total efficient pollution level. In particular, it only needs data on aggregate industry costs and benefits of externalities. This is an advantage of this approach compared to quotas or Pigouvian taxation.



# Public goods

## Definition

* Goods can be categorized by two properties:
    * Excludability
    * Rivality

* A good is said to be _excludable_ if it is possible to prevent an individual from enjoying it. Otherwise it is _nonexcludable_
    * Examples of excludable goods: essentially anything that is not freely accessible (access requires a payment, a password, etc.)
    * Examples of nonexludable goods: national defense, street lighting, clean air

* A good is said to be _rival_ (in consumption) if the consumption of the good of an agent reduces the amount available to other agents. Otherwise it is _nonrival_
    * Examples of rival goods: Most goods we consume on a daily basis (food, drinks, sweets, snacks, etc.)
    * Examples of nonrival goods: A movie on Netflix, an annoucement from a public radio, a software, the roads very early in the morning
    
## Categorization of goods

| | Excludable | Nonexcludable |
|:--|:--|:--|
|__Rival__|Private goods <br/> (Example: a cake)|Common resources <br/> (Example: fishing grounds)|
|__Non-rival__|Artificially scarce goods <br/> (Example: streaming services)|Public goods <br/> (Example: national defense)|

* Only private goods can be efficiently produced by the competitive market

* A good that is nonexcludable is subject to __freeriders__: individuals who do not pay or do not sufficiently contribute because they expect the others to do it
    * Can you think of an example?
    
* The competitive equilibrium quantity will generally be inefficiently low
<!--     * Nonexcludability: insufficient production
    * Nonrivality: insufficient consumption -->
    
## Free-riding of public goods

When goods are not excludable, they are subject to free-riding: the insufficient contribution of each consumer to the maintenance or replenishment of the goods. This is a common problem in practice. Let us illustrate it with a simple example.

::: {#exm-cleaning}

Consider two roommates who clean their apartment every Saturday.
Every roommate $i$ simultaneously and independently chooses the number of hours she spends cleaning, $h_i \in [0, \bar{h}]$ where $\bar{h}$ denotes the maximum time one can devote to housework.
More time devoted to cleaning means less time for leisure (which gives her disutility), but a cleaner leaving space gives her satistfaction.

Her utility from cleaning can thus be written as:
$$
u_i(h_i, h_j) = (\bar{h} - h_i) + \beta \ln(h_i + h_j),
$${#eq-ff_example}
where $\beta \ln(h_i + h_j)$ captures the pleasure derived from cleanliness which is increasing in $h_i, h_j$ and $\beta >0.$

Observe that this is a simultaneous-moves game with two players, the solution is the NE of the game, which can be found by first identifying the best response function of each player $BR_i(h_j).$

The BR function of $i$ is the optimal choice of $h_i$ as a function of $h_j$, which $i$ determines by maximizing @eq-ff_example subject to $h_i \in [0, \bar{h}].$ Observe that $u_i$ is strictly concave in $h_i$ given $h_j$, implying that the FOC is also sufficient.
The FOC for an interior solution gives:
$$
1 = \frac{\beta}{h_i + h_j}\\
\iff h_i(h_j) = \beta - h_j.
$${#eq-ff_FOC_i}
    
As the other friend increases cleaning time, individual $i$ will do the opposite: free-riding behavior.
In particular if $h_j \geq \beta$ then roommate $i$ will not spend time cleaning.
If $h_j=0$ it is in the best interest of $i$ to clean $h_i=\beta >0.$ Moreover $h_i$ increases in $\beta$ for any fixed $h_j.$
    
The NE of the game can be determined by solving for the system of equations involving the two BRs. By symmetry $h^*_i = h^*_j \equiv h^*.$
Substituting $h^*_i = h^*_j \equiv h^*$ into @eq-ff_FOC_i and simplying, we obtain:
$$
h^* = \frac{\beta}{2},
$$
which is strictly less than $\beta.$
    
For example, if $\beta=2$, then each flatmate will spend 1 hour cleaning in equilibrium.
:::

## Solutions to free-riding

One way to address free-riding is to require all individuals to pay for the good via taxes rather than voluntary contributions.
In the cleaning example, the two could draft the house rules specifiying that each flatmate spends exactly the same number of hours cleaning, even if one of them travels most of the week.

A less rigid solution is to require users to pay for every usage, such as
highway tolls, or entrance fees to public parks.
This works if "usage" is unambiguously defined; it could be tricky in the cleaning case (what if one travels half of the week? or having guests over?)

## Common resources

Common resources are highly vulnerable to overexploitation and depletion since they are rivalrous but non-excludable in consumption.
Examples of common resources include fish in a small lake, roads during traffic hours, etc.
When one agent consumes the good, she generates negative externalities by reducing the amount available to others.
    
<!-- * Some resources are renewable given sufficient time (trees in the forest, fish in the lake, etc.) while others are non-renewable (oil, natural minerals, etc.) -->

::: {#exm-common-resources}

Let $S > 0$ denote the resource stock, for example the number of fish in a lake, which we assume to be fixed on any given day.
Assume that $N$ individuals can fish in the lake
Fish once caught can be sold in a competitive fish market at competitive market price $p$ (fishers are price-takers)
The cost function of individual $i$ can be written as:
$$
C(q_i, Q_{-i}) = \frac{q_i(q_i + Q_{-i})}{S},
$${#eq-common_res_cost}
where $Q_{-i}=\sum_{j\neq i} q_j$ is the total quantity caught by individuals other than $i$.

@eq-common_res_cost says that:

  * The more fish the lake has, the easier it will be to catch one

  * The cost increases in the number of fish caught

  * The fewer the individuals, the easier (less costly in terms of time and effort, etc.) it will be to catch a fish
        
Every fisherman $i$ simultaneously and independently solves:
$$
\max_{q_i} \pi_i = p q_i - C(q_i, Q_{-i}).
$${#eq-common_res_PMP}
    
The necessary and sufficient condition for a max is:
$$
p = \frac{2q_i + Q_{-i}}{S}.
$${#eq-common_res_FOC}
    
@eq-common_res_FOC gives us the best-response function of each individual $i$:

$$
q_i(Q_{-i}) = \frac{pS - Q_{-i}}{2} = \frac{pS}{2} - \frac{Q_{-i}}{2}.
$${#eq-common_res_BR}
    

Rhe BR function tells us that:

* The individual appropriation $q_i$ increases in:
    * The market value of the resourch $p$
    * The amount of the resource available
* The individual appropriation decreases if other individuals' appropriation increases (negative externality)
    * It is an externality because it affects $q_i$ _not_ via the price $p$, which is taken as given
    * If $Q_{-i} \geq pS$, then $q_i = 0.$
        
Let us find the equilibrium appropriation by invoking symmetry:
$$
q^*_1 = q^*_2 = \dots = q^*_N = q^*.
$$
    
Substituting this into the BR function to obtain:
$$
2q^* = pS - (N-1)q^* \\
\iff q^* = \frac{pS}{N+1}.
$${#eq-common_res_NE}

Observe that the individual equilibrium appropriation increases in the resource stock but decreases in the number of individuals competing for it.
:::

## Common resources: Joint profit maximization

In the @exm-common-resources, individuals make decisions independently. 
If individuals coordinate on the level of appropriation to maximize joint profit, i.e., they can achieve even higher level of profits.
Interestingly, the joint venture also leads to _less intensive_ resource exploitation. Consider again the setting of @exm-common-resources but now suppose that fishermen decide on the level of appropriation to maximize _joint profits_.

The joint PMP is:
$$
\begin{aligned}
\max_{q_1,...,q_N} \pi &\equiv \sum_{i=1}^N \pi_i \\
&= \sum_{i=1}^N p q_i - \sum_{i=1}^N C(q_i, Q_{-i}) \\
&= pQ - \frac{Q^2}{S},
\end{aligned}
$${#eq-joint_PMP}
where $Q\equiv \sum_{i=1}^N q_i = q_i + Q_{-i}$ is the total appropriation.
        
The FOC w.r.t $q_i$ yields:
$$
p = \frac{2Q}{S} \\
\iff \frac{pS}{2} = q_i + Q_{-i} \\
\iff q_i = \frac{pS}{2} - Q_{-i}, 
$${#eq-joint_BR}
which is the best response function of $i$.
    
The equilibrium output is thus:
$$
    Nq^J = \frac{pS}{2} \iff q^J = \frac{pS}{2N}.
$${#eq-common_joint_eq}
    

Since $2N > N + 1$ for $N > 1$, we conclude that the joint equilibrium appropriation $q^J$ is strictly less than the independent equilibrium appropriation $q^*$ (@eq-common_res_NE).

Let us compare profits between the two cases.

In the case of independent exploitation:
  
$$
\pi^* = pq^* - \frac{N{q^*}^2}{S}.
$$
  
In the case of cooperative exploitation:
$$
\pi^J = pq^J - \frac{N{q^J}^2}{S}.
$$

The difference in profits is thus:
$$
\begin{aligned}
\pi^J - \pi^* &= -p(q^* - q^J) + \frac{N}{S}(q^* - q^J)^2 \\
&= \frac{1}{S}(q^* - q^J)[N(q^* + q^J) - pS]. 
\end{aligned}
$${#eq-prof_diff}
    
Note that the sign of $\pi^J - \pi^*$ depends on the sign of $[N(q^* + q^J) - pS].$ Observe that $pS = (N + 1)q^* = 2N q^J$, implying that we can write:
$$
pS = \frac{(N + 1)q^* + 2N q^J}{2}.
$${#eq-pS_exp}

Substituting @eq-pS_exp into the term inside the square bracket of @eq-prof_diff, we get:
$$
N(q^* + q^J) - \frac{(N + 1)q^* + 2N q^J}{2} \\
= \frac{2N q^* - (N + 1)q^*}{2} \\
= \frac{(N - 1)q^*}{2},
$$
which is strictly positive for $N>1.$
    
Hence cooperative profits are also greater. In other words, letting individuals form cooperatives to jointly exploit a common resource may alleviate the over-exploitation problem.

::: {#rem-common-resources}
Common resources are particularly vulnerable to over-exploitation due to their non-excludable and rivalrous properties.
If individuals independently decide on the amount to appropriate from the common resource stock, they will tend to take more than what is socially optimal. From our analyses we can propose two solutions, both of which aim at incentivizing individuals to internalize the externalities of their action:

  * Nationalization of the common resource
  * Assigning exclusive rights to cooperatives and not individuals to extract a common resource
:::

# Exercises

::: {#exr-car-accident}

Consider an economy with two individuals with preferences given by:
    
$$
u^i(s^i, q^i) = v^i(s^i) + \alpha w^i, \quad i=A, B,
$$
    
where $s^i$ denote the speed at which individual $i$ drives, $w^i$ is his wealth and $\alpha > 0.$ Assume $v^i$ is strictly increasing and concave in $s^i.$ The probability of accident $p(s^A, s^B)$ depends on the driving speed of both. In particular:
$$
p_i \equiv \frac{\partial p}{\partial s^i} > 0,\quad i=A,B.
$$
    
When an accident occurs, individual $i$ incurs a cost of damage $c^i > 0.$
  
Determine the competitive equilibrium speeds and the socially optimal ones. Which one is greater? If the government wishes to restore social effciency by imposing a fine, how large must it be? For simplicity assume that $p_i = \beta_i = const>0.$ 
:::